var log = require( 'ringo/logging' ).getLogger( module.id );
var httpClient = require( 'ringo/httpclient' );

exports.Service = Object.subClass( {

    init : function ( auth ) {

    },

    read : function () {
        var opts = {
            url: 'http://www.google.com/m8/feeds',
            headers: {
                'Authorization': 'Bearer ' + Oauth_token,
                'GData-version': '3.0'
            }
        };

        var request = httpClient.request(opts);

        return request.content;
    },

    write : function ( contacts ) {
        var opts = {
            url: '',
            headers: {
                'Authorization': 'Bearer ' + Oauth_token,
                'GData-version': '3.0'
            }
        };

        var request = httpClient.request(opts);

        return request.content;
    }
} );

obj = {
    "version":"1.0",
    "encoding":"UTF-8",
    "feed":{
        "xmlns":"http://www.w3.org/2005/Atom",
        "xmlns$openSearch":"http://a9.com/-/spec/opensearch/1.1/",
        "xmlns$gContact":"http://schemas.google.com/contact/2008",
        "xmlns$batch":"http://schemas.google.com/gdata/batch",
        "xmlns$gd":"http://schemas.google.com/g/2005",
        "gd$etag":"W/\"Ck4HRH4-cCt7I2A9WhBaEEo.\"",
        "id":{
            "$t":"anthonyclever@gmail.com"
        },
        "updated":{
            "$t":"2013-05-20T17:28:55.058Z"
        },
        "category":[
            {
                "scheme":"http://schemas.google.com/g/2005#kind",
                "term":"http://schemas.google.com/contact/2008#contact"
            }
        ],
        "title":{
            "$t":"Anthony.Clever's Contacts"
        },
        "link":[
            {
                "rel":"alternate",
                "type":"text/html",
                "href":"http://www.google.com/"
            },
            {
                "rel":"http://schemas.google.com/g/2005#feed",
                "type":"application/atom+xml",
                "href":"https://www.google.com/m8/feeds/contacts/anthonyclever%40gmail.com/full"
            },
            {
                "rel":"http://schemas.google.com/g/2005#post",
                "type":"application/atom+xml",
                "href":"https://www.google.com/m8/feeds/contacts/anthonyclever%40gmail.com/full"
            },
            {
                "rel":"http://schemas.google.com/g/2005#batch",
                "type":"application/atom+xml",
                "href":"https://www.google.com/m8/feeds/contacts/anthonyclever%40gmail.com/full/batch"
            },
            {
                "rel":"self",
                "type":"application/atom+xml",
                "href":"https://www.google.com/m8/feeds/contacts/anthonyclever%40gmail.com/full?alt\u003djson\u0026max-results\u003d25"
            }
        ],
        "author":[
            {
                "name":{
                    "$t":"Anthony.Clever"
                },
                "email":{
                    "$t":"anthonyclever@gmail.com"
                }
            }
        ],
        "generator":{
            "version":"1.0",
            "uri":"http://www.google.com/m8/feeds",
            "$t":"Contacts"
        },
        "openSearch$totalResults":{
            "$t":"19"
        },
        "openSearch$startIndex":{
            "$t":"1"
        },
        "openSearch$itemsPerPage":{
            "$t":"25"
        },
        "entry":[
            {
                "gd$etag":"\"RHk_fjVSLyt7I2A9WhdXEk8DRgc.\"",
                "id":{
                    "$t":"http://www.google.com/m8/feeds/contacts/anthonyclever%40gmail.com/base/0"
                },
                "updated":{
                    "$t":"2011-08-24T23:38:55.746Z"
                },
                "app$edited":{
                    "xmlns$app":"http://www.w3.org/2007/app",
                    "$t":"2011-08-24T23:38:55.746Z"
                },
                "category":[
                    {
                        "scheme":"http://schemas.google.com/g/2005#kind",
                        "term":"http://schemas.google.com/contact/2008#contact"
                    }
                ],
                "title":{
                    "$t":"Janice Clever"
                },
                "content":{
                    "$t":""
                },
                "link":[
                    {
                        "rel":"http://schemas.google.com/contacts/2008/rel#photo",
                        "type":"image/*",
                        "href":"https://www.google.com/m8/feeds/photos/media/anthonyclever%40gmail.com/0"
                    },
                    {
                        "rel":"self",
                        "type":"application/atom+xml",
                        "href":"https://www.google.com/m8/feeds/contacts/anthonyclever%40gmail.com/full/0"
                    },
                    {
                        "rel":"edit",
                        "type":"application/atom+xml",
                        "href":"https://www.google.com/m8/feeds/contacts/anthonyclever%40gmail.com/full/0"
                    }
                ],
                "gd$name":{
                    "gd$fullName":{
                        "$t":"Janice Clever"
                    },
                    "gd$givenName":{
                        "$t":"Janice"
                    },
                    "gd$familyName":{
                        "$t":"Clever"
                    }
                },
                "gd$phoneNumber":[
                    {
                        "rel":"http://schemas.google.com/g/2005#mobile",
                        "$t":"13373685448"
                    }
                ],
                "gContact$groupMembershipInfo":[
                    {
                        "deleted":"false",
                        "href":"http://www.google.com/m8/feeds/groups/anthonyclever%40gmail.com/base/6"
                    },
                    {
                        "deleted":"false",
                        "href":"http://www.google.com/m8/feeds/groups/anthonyclever%40gmail.com/base/20dd23b50bdaba24"
                    }
                ]
            },
            {
                "gd$etag":"\"QX0zejVRLSt7I2A9WhJbEkoITgc.\"",
                "id":{
                    "$t":"http://www.google.com/m8/feeds/contacts/anthonyclever%40gmail.com/base/4"
                },
                "updated":{
                    "$t":"2012-09-22T00:15:30.382Z"
                },
                "app$edited":{
                    "xmlns$app":"http://www.w3.org/2007/app",
                    "$t":"2012-09-22T00:15:30.382Z"
                },
                "category":[
                    {
                        "scheme":"http://schemas.google.com/g/2005#kind",
                        "term":"http://schemas.google.com/contact/2008#contact"
                    }
                ],
                "title":{
                    "$t":"David Chen"
                },
                "link":[
                    {
                        "rel":"http://schemas.google.com/contacts/2008/rel#photo",
                        "type":"image/*",
                        "href":"https://www.google.com/m8/feeds/photos/media/anthonyclever%40gmail.com/4",
                        "gd$etag":"\"JzBXO1wCbCt7I2BPDUQsTUlCAFkyKlkNWhs.\""
                    },
                    {
                        "rel":"self",
                        "type":"application/atom+xml",
                        "href":"https://www.google.com/m8/feeds/contacts/anthonyclever%40gmail.com/full/4"
                    },
                    {
                        "rel":"edit",
                        "type":"application/atom+xml",
                        "href":"https://www.google.com/m8/feeds/contacts/anthonyclever%40gmail.com/full/4"
                    }
                ],
                "gd$name":{
                    "gd$fullName":{
                        "$t":"David Chen"
                    },
                    "gd$givenName":{
                        "$t":"David"
                    },
                    "gd$familyName":{
                        "$t":"Chen"
                    }
                },
                "gd$email":[
                    {
                        "rel":"http://schemas.google.com/g/2005#other",
                        "address":"mistaninja@gmail.com",
                        "primary":"true"
                    }
                ],
                "gContact$website":[
                    {
                        "href":"http://www.google.com/profiles/117862939701571855466",
                        "rel":"profile"
                    }
                ]
            },
            {
                "gd$etag":"\"QX0zejVRLSt7I2A9WhJbEkoITgc.\"",
                "id":{
                    "$t":"http://www.google.com/m8/feeds/contacts/anthonyclever%40gmail.com/base/7"
                },
                "updated":{
                    "$t":"2012-09-22T00:15:30.382Z"
                },
                "app$edited":{
                    "xmlns$app":"http://www.w3.org/2007/app",
                    "$t":"2012-09-22T00:15:30.382Z"
                },
                "category":[
                    {
                        "scheme":"http://schemas.google.com/g/2005#kind",
                        "term":"http://schemas.google.com/contact/2008#contact"
                    }
                ],
                "title":{
                    "$t":"Danny Martin"
                },
                "link":[
                    {
                        "rel":"http://schemas.google.com/contacts/2008/rel#photo",
                        "type":"image/*",
                        "href":"https://www.google.com/m8/feeds/photos/media/anthonyclever%40gmail.com/7",
                        "gd$etag":"\"cBJDGmQKfCt7I2BdKnACZwh_WnkoIUoOYlE.\""
                    },
                    {
                        "rel":"self",
                        "type":"application/atom+xml",
                        "href":"https://www.google.com/m8/feeds/contacts/anthonyclever%40gmail.com/full/7"
                    },
                    {
                        "rel":"edit",
                        "type":"application/atom+xml",
                        "href":"https://www.google.com/m8/feeds/contacts/anthonyclever%40gmail.com/full/7"
                    }
                ],
                "gd$name":{
                    "gd$fullName":{
                        "$t":"Danny Martin"
                    },
                    "gd$givenName":{
                        "$t":"Danny"
                    },
                    "gd$familyName":{
                        "$t":"Martin"
                    }
                },
                "gd$email":[
                    {
                        "rel":"http://schemas.google.com/g/2005#other",
                        "address":"flamingmono@gmail.com",
                        "primary":"true"
                    }
                ],
                "gd$phoneNumber":[
                    {
                        "rel":"http://schemas.google.com/g/2005#mobile",
                        "$t":"17176493596"
                    }
                ],
                "gContact$groupMembershipInfo":[
                    {
                        "deleted":"false",
                        "href":"http://www.google.com/m8/feeds/groups/anthonyclever%40gmail.com/base/6"
                    }
                ]
            },
            {
                "gd$etag":"\"SH07ejVSLit7I2A9WhdXGE4CRgM.\"",
                "id":{
                    "$t":"http://www.google.com/m8/feeds/contacts/anthonyclever%40gmail.com/base/41d6c138e0f7172"
                },
                "updated":{
                    "$t":"2011-09-01T00:49:39.302Z"
                },
                "app$edited":{
                    "xmlns$app":"http://www.w3.org/2007/app",
                    "$t":"2011-09-01T00:49:39.302Z"
                },
                "category":[
                    {
                        "scheme":"http://schemas.google.com/g/2005#kind",
                        "term":"http://schemas.google.com/contact/2008#contact"
                    }
                ],
                "title":{
                    "$t":"SusanExpress"
                },
                "link":[
                    {
                        "rel":"http://schemas.google.com/contacts/2008/rel#photo",
                        "type":"image/*",
                        "href":"https://www.google.com/m8/feeds/photos/media/anthonyclever%40gmail.com/41d6c138e0f7172"
                    },
                    {
                        "rel":"self",
                        "type":"application/atom+xml",
                        "href":"https://www.google.com/m8/feeds/contacts/anthonyclever%40gmail.com/full/41d6c138e0f7172"
                    },
                    {
                        "rel":"edit",
                        "type":"application/atom+xml",
                        "href":"https://www.google.com/m8/feeds/contacts/anthonyclever%40gmail.com/full/41d6c138e0f7172"
                    }
                ],
                "gd$name":{
                    "gd$fullName":{
                        "$t":"SusanExpress"
                    },
                    "gd$givenName":{
                        "$t":"SusanExpress"
                    }
                },
                "gd$email":[
                    {
                        "rel":"http://schemas.google.com/g/2005#other",
                        "address":"sales@susanexpress.com",
                        "primary":"true"
                    }
                ]
            },
            {
                "gd$etag":"\"QXk9eDVSLyt7I2A9WxBREEwDRgQ.\"",
                "id":{
                    "$t":"http://www.google.com/m8/feeds/contacts/anthonyclever%40gmail.com/base/7576a3b0813ad2a"
                },
                "updated":{
                    "$t":"2009-12-28T16:51:40.760Z"
                },
                "app$edited":{
                    "xmlns$app":"http://www.w3.org/2007/app",
                    "$t":"2009-12-28T16:51:40.760Z"
                },
                "category":[
                    {
                        "scheme":"http://schemas.google.com/g/2005#kind",
                        "term":"http://schemas.google.com/contact/2008#contact"
                    }
                ],
                "title":{
                    "$t":"Daniel Mosier"
                },
                "link":[
                    {
                        "rel":"http://schemas.google.com/contacts/2008/rel#photo",
                        "type":"image/*",
                        "href":"https://www.google.com/m8/feeds/photos/media/anthonyclever%40gmail.com/7576a3b0813ad2a"
                    },
                    {
                        "rel":"self",
                        "type":"application/atom+xml",
                        "href":"https://www.google.com/m8/feeds/contacts/anthonyclever%40gmail.com/full/7576a3b0813ad2a"
                    },
                    {
                        "rel":"edit",
                        "type":"application/atom+xml",
                        "href":"https://www.google.com/m8/feeds/contacts/anthonyclever%40gmail.com/full/7576a3b0813ad2a"
                    }
                ],
                "gd$name":{
                    "gd$fullName":{
                        "$t":"Daniel Mosier"
                    },
                    "gd$givenName":{
                        "$t":"Daniel"
                    },
                    "gd$familyName":{
                        "$t":"Mosier"
                    }
                },
                "gd$phoneNumber":[
                    {
                        "rel":"http://schemas.google.com/g/2005#mobile",
                        "$t":"19096316495"
                    }
                ],
                "gContact$groupMembershipInfo":[
                    {
                        "deleted":"false",
                        "href":"http://www.google.com/m8/feeds/groups/anthonyclever%40gmail.com/base/6"
                    }
                ]
            },
            {
                "gd$etag":"\"SXg8cTVSLit7I2A9WhJXEkQJRQY.\"",
                "id":{
                    "$t":"http://www.google.com/m8/feeds/contacts/anthonyclever%40gmail.com/base/76dbe6b0a7294c8"
                },
                "updated":{
                    "$t":"2012-08-06T22:47:08.679Z"
                },
                "app$edited":{
                    "xmlns$app":"http://www.w3.org/2007/app",
                    "$t":"2012-08-06T22:47:08.679Z"
                },
                "category":[
                    {
                        "scheme":"http://schemas.google.com/g/2005#kind",
                        "term":"http://schemas.google.com/contact/2008#contact"
                    }
                ],
                "title":{
                    "$t":""
                },
                "link":[
                    {
                        "rel":"http://schemas.google.com/contacts/2008/rel#photo",
                        "type":"image/*",
                        "href":"https://www.google.com/m8/feeds/photos/media/anthonyclever%40gmail.com/76dbe6b0a7294c8",
                        "gd$etag":"\"KBhGFVkTbCt7I2B5I0oRTy1VTlo7eXgbMSE.\""
                    },
                    {
                        "rel":"self",
                        "type":"application/atom+xml",
                        "href":"https://www.google.com/m8/feeds/contacts/anthonyclever%40gmail.com/full/76dbe6b0a7294c8"
                    },
                    {
                        "rel":"edit",
                        "type":"application/atom+xml",
                        "href":"https://www.google.com/m8/feeds/contacts/anthonyclever%40gmail.com/full/76dbe6b0a7294c8"
                    }
                ],
                "gd$email":[
                    {
                        "rel":"http://schemas.google.com/g/2005#other",
                        "address":"anthonyclever@gmail.com",
                        "primary":"true"
                    }
                ]
            },
            {
                "gd$etag":"\"R347cTVSLit7I2A9WhJQEEUNRwQ.\"",
                "id":{
                    "$t":"http://www.google.com/m8/feeds/contacts/anthonyclever%40gmail.com/base/f6f26438c2aacd6"
                },
                "updated":{
                    "$t":"2012-07-23T23:43:26.009Z"
                },
                "app$edited":{
                    "xmlns$app":"http://www.w3.org/2007/app",
                    "$t":"2012-07-23T23:43:26.009Z"
                },
                "category":[
                    {
                        "scheme":"http://schemas.google.com/g/2005#kind",
                        "term":"http://schemas.google.com/contact/2008#contact"
                    }
                ],
                "title":{
                    "$t":""
                },
                "link":[
                    {
                        "rel":"http://schemas.google.com/contacts/2008/rel#photo",
                        "type":"image/*",
                        "href":"https://www.google.com/m8/feeds/photos/media/anthonyclever%40gmail.com/f6f26438c2aacd6"
                    },
                    {
                        "rel":"self",
                        "type":"application/atom+xml",
                        "href":"https://www.google.com/m8/feeds/contacts/anthonyclever%40gmail.com/full/f6f26438c2aacd6"
                    },
                    {
                        "rel":"edit",
                        "type":"application/atom+xml",
                        "href":"https://www.google.com/m8/feeds/contacts/anthonyclever%40gmail.com/full/f6f26438c2aacd6"
                    }
                ],
                "gd$email":[
                    {
                        "rel":"http://schemas.google.com/g/2005#other",
                        "address":"charles@grunwald.me",
                        "primary":"true"
                    }
                ]
            },
            {
                "gd$etag":"\"SXs7ejVSLyt7I2A9WxVaEEoLTgA.\"",
                "id":{
                    "$t":"http://www.google.com/m8/feeds/contacts/anthonyclever%40gmail.com/base/2c34c586889ad07e"
                },
                "updated":{
                    "$t":"2009-04-07T02:39:08.502Z"
                },
                "app$edited":{
                    "xmlns$app":"http://www.w3.org/2007/app",
                    "$t":"2009-04-07T02:39:08.502Z"
                },
                "category":[
                    {
                        "scheme":"http://schemas.google.com/g/2005#kind",
                        "term":"http://schemas.google.com/contact/2008#contact"
                    }
                ],
                "title":{
                    "$t":"Cheryl Powell"
                },
                "link":[
                    {
                        "rel":"http://schemas.google.com/contacts/2008/rel#photo",
                        "type":"image/*",
                        "href":"https://www.google.com/m8/feeds/photos/media/anthonyclever%40gmail.com/2c34c586889ad07e"
                    },
                    {
                        "rel":"self",
                        "type":"application/atom+xml",
                        "href":"https://www.google.com/m8/feeds/contacts/anthonyclever%40gmail.com/full/2c34c586889ad07e"
                    },
                    {
                        "rel":"edit",
                        "type":"application/atom+xml",
                        "href":"https://www.google.com/m8/feeds/contacts/anthonyclever%40gmail.com/full/2c34c586889ad07e"
                    }
                ],
                "gd$name":{
                    "gd$fullName":{
                        "$t":"Cheryl Powell"
                    },
                    "gd$givenName":{
                        "$t":"Cheryl"
                    },
                    "gd$familyName":{
                        "$t":"Powell"
                    }
                },
                "gd$email":[
                    {
                        "rel":"http://schemas.google.com/g/2005#other",
                        "address":"drchief@embarqmail.com"
                    }
                ],
                "gContact$groupMembershipInfo":[
                    {
                        "deleted":"false",
                        "href":"http://www.google.com/m8/feeds/groups/anthonyclever%40gmail.com/base/6"
                    }
                ]
            },
            {
                "gd$etag":"\"RXY8fTVSLyt7I2A9Wx5bGUwPRAE.\"",
                "id":{
                    "$t":"http://www.google.com/m8/feeds/contacts/anthonyclever%40gmail.com/base/43d3fd9d893bea78"
                },
                "updated":{
                    "$t":"2010-11-05T00:02:34.875Z"
                },
                "app$edited":{
                    "xmlns$app":"http://www.w3.org/2007/app",
                    "$t":"2010-11-05T00:02:34.875Z"
                },
                "category":[
                    {
                        "scheme":"http://schemas.google.com/g/2005#kind",
                        "term":"http://schemas.google.com/contact/2008#contact"
                    }
                ],
                "title":{
                    "$t":"Daniel Mosier"
                },
                "link":[
                    {
                        "rel":"http://schemas.google.com/contacts/2008/rel#photo",
                        "type":"image/*",
                        "href":"https://www.google.com/m8/feeds/photos/media/anthonyclever%40gmail.com/43d3fd9d893bea78"
                    },
                    {
                        "rel":"self",
                        "type":"application/atom+xml",
                        "href":"https://www.google.com/m8/feeds/contacts/anthonyclever%40gmail.com/full/43d3fd9d893bea78"
                    },
                    {
                        "rel":"edit",
                        "type":"application/atom+xml",
                        "href":"https://www.google.com/m8/feeds/contacts/anthonyclever%40gmail.com/full/43d3fd9d893bea78"
                    }
                ],
                "gd$name":{
                    "gd$fullName":{
                        "$t":"Daniel Mosier"
                    },
                    "gd$givenName":{
                        "$t":"Daniel"
                    },
                    "gd$familyName":{
                        "$t":"Mosier"
                    }
                },
                "gd$email":[
                    {
                        "rel":"http://schemas.google.com/g/2005#other",
                        "address":"reisom57@gmail.com"
                    }
                ],
                "gContact$groupMembershipInfo":[
                    {
                        "deleted":"false",
                        "href":"http://www.google.com/m8/feeds/groups/anthonyclever%40gmail.com/base/6"
                    },
                    {
                        "deleted":"false",
                        "href":"http://www.google.com/m8/feeds/groups/anthonyclever%40gmail.com/base/3dd334388e9307e2"
                    }
                ]
            },
            {
                "gd$etag":"\"RX4_cDVSLit7I2A9WhdXEk8DRgc.\"",
                "id":{
                    "$t":"http://www.google.com/m8/feeds/contacts/anthonyclever%40gmail.com/base/46efd7f3087d8aff"
                },
                "updated":{
                    "$t":"2011-08-24T23:38:54.048Z"
                },
                "app$edited":{
                    "xmlns$app":"http://www.w3.org/2007/app",
                    "$t":"2011-08-24T23:38:54.048Z"
                },
                "category":[
                    {
                        "scheme":"http://schemas.google.com/g/2005#kind",
                        "term":"http://schemas.google.com/contact/2008#contact"
                    }
                ],
                "title":{
                    "$t":"Janice Clever"
                },
                "content":{
                    "$t":""
                },
                "link":[
                    {
                        "rel":"http://schemas.google.com/contacts/2008/rel#photo",
                        "type":"image/*",
                        "href":"https://www.google.com/m8/feeds/photos/media/anthonyclever%40gmail.com/46efd7f3087d8aff"
                    },
                    {
                        "rel":"self",
                        "type":"application/atom+xml",
                        "href":"https://www.google.com/m8/feeds/contacts/anthonyclever%40gmail.com/full/46efd7f3087d8aff"
                    },
                    {
                        "rel":"edit",
                        "type":"application/atom+xml",
                        "href":"https://www.google.com/m8/feeds/contacts/anthonyclever%40gmail.com/full/46efd7f3087d8aff"
                    }
                ],
                "gd$name":{
                    "gd$fullName":{
                        "$t":"Janice Clever"
                    },
                    "gd$givenName":{
                        "$t":"Janice"
                    },
                    "gd$familyName":{
                        "$t":"Clever"
                    }
                },
                "gContact$groupMembershipInfo":[
                    {
                        "deleted":"false",
                        "href":"http://www.google.com/m8/feeds/groups/anthonyclever%40gmail.com/base/20dd23b50bdaba24"
                    }
                ]
            },
            {
                "gd$etag":"\"QX48ejVSLit7I2A9WhVbGEgJQwM.\"",
                "id":{
                    "$t":"http://www.google.com/m8/feeds/contacts/anthonyclever%40gmail.com/base/491767848c095a4e"
                },
                "updated":{
                    "$t":"2012-06-04T23:44:30.072Z"
                },
                "app$edited":{
                    "xmlns$app":"http://www.w3.org/2007/app",
                    "$t":"2012-06-04T23:44:30.072Z"
                },
                "category":[
                    {
                        "scheme":"http://schemas.google.com/g/2005#kind",
                        "term":"http://schemas.google.com/contact/2008#contact"
                    }
                ],
                "title":{
                    "$t":""
                },
                "link":[
                    {
                        "rel":"http://schemas.google.com/contacts/2008/rel#photo",
                        "type":"image/*",
                        "href":"https://www.google.com/m8/feeds/photos/media/anthonyclever%40gmail.com/491767848c095a4e"
                    },
                    {
                        "rel":"self",
                        "type":"application/atom+xml",
                        "href":"https://www.google.com/m8/feeds/contacts/anthonyclever%40gmail.com/full/491767848c095a4e"
                    },
                    {
                        "rel":"edit",
                        "type":"application/atom+xml",
                        "href":"https://www.google.com/m8/feeds/contacts/anthonyclever%40gmail.com/full/491767848c095a4e"
                    }
                ],
                "gd$email":[
                    {
                        "rel":"http://schemas.google.com/g/2005#other",
                        "address":"dotconnexion@gmail.com",
                        "primary":"true"
                    }
                ]
            },
            {
                "gd$etag":"\"R3o5fDVSLit7I2A9WhdXEkoOTgc.\"",
                "id":{
                    "$t":"http://www.google.com/m8/feeds/contacts/anthonyclever%40gmail.com/base/49601c470fb7ff98"
                },
                "updated":{
                    "$t":"2011-08-25T12:22:16.424Z"
                },
                "app$edited":{
                    "xmlns$app":"http://www.w3.org/2007/app",
                    "$t":"2011-08-25T12:22:16.424Z"
                },
                "category":[
                    {
                        "scheme":"http://schemas.google.com/g/2005#kind",
                        "term":"http://schemas.google.com/contact/2008#contact"
                    }
                ],
                "title":{
                    "$t":"Linda Clever"
                },
                "content":{
                    "$t":""
                },
                "link":[
                    {
                        "rel":"http://schemas.google.com/contacts/2008/rel#photo",
                        "type":"image/*",
                        "href":"https://www.google.com/m8/feeds/photos/media/anthonyclever%40gmail.com/49601c470fb7ff98"
                    },
                    {
                        "rel":"self",
                        "type":"application/atom+xml",
                        "href":"https://www.google.com/m8/feeds/contacts/anthonyclever%40gmail.com/full/49601c470fb7ff98"
                    },
                    {
                        "rel":"edit",
                        "type":"application/atom+xml",
                        "href":"https://www.google.com/m8/feeds/contacts/anthonyclever%40gmail.com/full/49601c470fb7ff98"
                    }
                ],
                "gd$name":{
                    "gd$fullName":{
                        "$t":"Linda Clever"
                    },
                    "gd$givenName":{
                        "$t":"Linda"
                    },
                    "gd$familyName":{
                        "$t":"Clever"
                    }
                },
                "gd$organization":[
                    {
                        "rel":"http://schemas.google.com/g/2005#other",
                        "gd$orgName":{
                            "$t":"Linda John Hairstyling"
                        }
                    }
                ],
                "gd$phoneNumber":[
                    {
                        "rel":"http://schemas.google.com/g/2005#work",
                        "$t":"13372380051"
                    },
                    {
                        "rel":"http://schemas.google.com/g/2005#mobile",
                        "$t":"13373150761"
                    }
                ],
                "gContact$groupMembershipInfo":[
                    {
                        "deleted":"false",
                        "href":"http://www.google.com/m8/feeds/groups/anthonyclever%40gmail.com/base/6"
                    }
                ]
            },
            {
                "gd$etag":"\"QXY-eTVSLSt7I2A9Wx5bGUwKQAQ.\"",
                "id":{
                    "$t":"http://www.google.com/m8/feeds/contacts/anthonyclever%40gmail.com/base/526bd7f5085d8549"
                },
                "updated":{
                    "$t":"2010-11-04T22:45:00.851Z"
                },
                "app$edited":{
                    "xmlns$app":"http://www.w3.org/2007/app",
                    "$t":"2010-11-04T22:45:00.851Z"
                },
                "category":[
                    {
                        "scheme":"http://schemas.google.com/g/2005#kind",
                        "term":"http://schemas.google.com/contact/2008#contact"
                    }
                ],
                "title":{
                    "$t":"Michael Mackenzie"
                },
                "link":[
                    {
                        "rel":"http://schemas.google.com/contacts/2008/rel#photo",
                        "type":"image/*",
                        "href":"https://www.google.com/m8/feeds/photos/media/anthonyclever%40gmail.com/526bd7f5085d8549"
                    },
                    {
                        "rel":"self",
                        "type":"application/atom+xml",
                        "href":"https://www.google.com/m8/feeds/contacts/anthonyclever%40gmail.com/full/526bd7f5085d8549"
                    },
                    {
                        "rel":"edit",
                        "type":"application/atom+xml",
                        "href":"https://www.google.com/m8/feeds/contacts/anthonyclever%40gmail.com/full/526bd7f5085d8549"
                    }
                ],
                "gd$name":{
                    "gd$fullName":{
                        "$t":"Michael Mackenzie"
                    },
                    "gd$givenName":{
                        "$t":"Michael"
                    },
                    "gd$familyName":{
                        "$t":"Mackenzie"
                    }
                },
                "gd$email":[
                    {
                        "rel":"http://schemas.google.com/g/2005#other",
                        "address":"muffinger@gmail.com",
                        "primary":"true"
                    }
                ]
            },
            {
                "gd$etag":"\"Rn89eTZXLSt7I2A9WhNaF0UMTwU.\"",
                "id":{
                    "$t":"http://www.google.com/m8/feeds/contacts/anthonyclever%40gmail.com/base/5438092989d2fa9e"
                },
                "updated":{
                    "$t":"2013-02-02T06:33:37.161Z"
                },
                "app$edited":{
                    "xmlns$app":"http://www.w3.org/2007/app",
                    "$t":"2013-02-02T06:33:37.161Z"
                },
                "category":[
                    {
                        "scheme":"http://schemas.google.com/g/2005#kind",
                        "term":"http://schemas.google.com/contact/2008#contact"
                    }
                ],
                "title":{
                    "$t":"John Clever Jr."
                },
                "content":{
                    "$t":""
                },
                "link":[
                    {
                        "rel":"http://schemas.google.com/contacts/2008/rel#photo",
                        "type":"image/*",
                        "href":"https://www.google.com/m8/feeds/photos/media/anthonyclever%40gmail.com/5438092989d2fa9e"
                    },
                    {
                        "rel":"self",
                        "type":"application/atom+xml",
                        "href":"https://www.google.com/m8/feeds/contacts/anthonyclever%40gmail.com/full/5438092989d2fa9e"
                    },
                    {
                        "rel":"edit",
                        "type":"application/atom+xml",
                        "href":"https://www.google.com/m8/feeds/contacts/anthonyclever%40gmail.com/full/5438092989d2fa9e"
                    }
                ],
                "gd$name":{
                    "gd$fullName":{
                        "$t":"John Clever Jr."
                    },
                    "gd$givenName":{
                        "$t":"John"
                    },
                    "gd$additionalName":{
                        "$t":"Clever"
                    },
                    "gd$familyName":{
                        "$t":"Jr."
                    }
                },
                "gd$organization":[
                    {
                        "rel":"http://schemas.google.com/g/2005#other",
                        "gd$orgName":{
                            "$t":"Surplus Warehouse"
                        }
                    }
                ],
                "gd$email":[
                    {
                        "rel":"http://schemas.google.com/g/2005#home",
                        "address":"Johnclev@gmail.com",
                        "primary":"true"
                    }
                ],
                "gd$phoneNumber":[
                    {
                        "rel":"http://schemas.google.com/g/2005#work",
                        "$t":"13372320346"
                    },
                    {
                        "rel":"http://schemas.google.com/g/2005#mobile",
                        "$t":"1-337-298-6734"
                    }
                ],
                "gd$structuredPostalAddress":[
                    {
                        "rel":"http://schemas.google.com/g/2005#home",
                        "gd$formattedAddress":{
                            "$t":"6374 Wilson Rd.\nMaurice, LA 70555"
                        },
                        "gd$street":{
                            "$t":"6374 Wilson Rd."
                        },
                        "gd$postcode":{
                            "$t":"70555"
                        },
                        "gd$city":{
                            "$t":"Maurice"
                        },
                        "gd$region":{
                            "$t":"LA"
                        }
                    },
                    {
                        "rel":"http://schemas.google.com/g/2005#other",
                        "gd$formattedAddress":{
                            "$t":"P.O. Box 284 \nMaurice LA, 70555"
                        },
                        "gd$street":{
                            "$t":"P.O. Box 284"
                        },
                        "gd$postcode":{
                            "$t":"70555"
                        },
                        "gd$city":{
                            "$t":"Maurice"
                        },
                        "gd$region":{
                            "$t":"LA"
                        }
                    }
                ],
                "gContact$groupMembershipInfo":[
                    {
                        "deleted":"false",
                        "href":"http://www.google.com/m8/feeds/groups/anthonyclever%40gmail.com/base/6"
                    },
                    {
                        "deleted":"false",
                        "href":"http://www.google.com/m8/feeds/groups/anthonyclever%40gmail.com/base/20dd23b50bdaba24"
                    }
                ]
            },
            {
                "gd$etag":"\"QHw6fTVSLSt7I2A9WhVQGE8MRQE.\"",
                "id":{
                    "$t":"http://www.google.com/m8/feeds/contacts/anthonyclever%40gmail.com/base/5777958c8a65aeb4"
                },
                "updated":{
                    "$t":"2012-04-07T19:17:31.215Z"
                },
                "app$edited":{
                    "xmlns$app":"http://www.w3.org/2007/app",
                    "$t":"2012-04-07T19:17:31.215Z"
                },
                "category":[
                    {
                        "scheme":"http://schemas.google.com/g/2005#kind",
                        "term":"http://schemas.google.com/contact/2008#contact"
                    }
                ],
                "title":{
                    "$t":"Todd Barchok"
                },
                "link":[
                    {
                        "rel":"http://schemas.google.com/contacts/2008/rel#photo",
                        "type":"image/*",
                        "href":"https://www.google.com/m8/feeds/photos/media/anthonyclever%40gmail.com/5777958c8a65aeb4"
                    },
                    {
                        "rel":"self",
                        "type":"application/atom+xml",
                        "href":"https://www.google.com/m8/feeds/contacts/anthonyclever%40gmail.com/full/5777958c8a65aeb4"
                    },
                    {
                        "rel":"edit",
                        "type":"application/atom+xml",
                        "href":"https://www.google.com/m8/feeds/contacts/anthonyclever%40gmail.com/full/5777958c8a65aeb4"
                    }
                ],
                "gd$name":{
                    "gd$fullName":{
                        "$t":"Todd Barchok"
                    },
                    "gd$givenName":{
                        "$t":"Todd"
                    },
                    "gd$familyName":{
                        "$t":"Barchok"
                    }
                },
                "gd$phoneNumber":[
                    {
                        "rel":"http://schemas.google.com/g/2005#mobile",
                        "$t":"614-315-8221"
                    }
                ],
                "gContact$groupMembershipInfo":[
                    {
                        "deleted":"false",
                        "href":"http://www.google.com/m8/feeds/groups/anthonyclever%40gmail.com/base/6"
                    }
                ]
            },
            {
                "gd$etag":"\"SXs7fzVSLit7I2A9WhRaEUUKQQ0.\"",
                "id":{
                    "$t":"http://www.google.com/m8/feeds/contacts/anthonyclever%40gmail.com/base/5f82af2c0a3a0672"
                },
                "updated":{
                    "$t":"2012-02-14T00:51:38.507Z"
                },
                "app$edited":{
                    "xmlns$app":"http://www.w3.org/2007/app",
                    "$t":"2012-02-14T00:51:38.507Z"
                },
                "category":[
                    {
                        "scheme":"http://schemas.google.com/g/2005#kind",
                        "term":"http://schemas.google.com/contact/2008#contact"
                    }
                ],
                "title":{
                    "$t":""
                },
                "link":[
                    {
                        "rel":"http://schemas.google.com/contacts/2008/rel#photo",
                        "type":"image/*",
                        "href":"https://www.google.com/m8/feeds/photos/media/anthonyclever%40gmail.com/5f82af2c0a3a0672"
                    },
                    {
                        "rel":"self",
                        "type":"application/atom+xml",
                        "href":"https://www.google.com/m8/feeds/contacts/anthonyclever%40gmail.com/full/5f82af2c0a3a0672"
                    },
                    {
                        "rel":"edit",
                        "type":"application/atom+xml",
                        "href":"https://www.google.com/m8/feeds/contacts/anthonyclever%40gmail.com/full/5f82af2c0a3a0672"
                    }
                ],
                "gd$email":[
                    {
                        "rel":"http://schemas.google.com/g/2005#other",
                        "address":"ryan@thingswith.us",
                        "primary":"true"
                    }
                ]
            },
            {
                "gd$etag":"\"RHkzfTVSLit7I2A9WhdXGUwLQgc.\"",
                "id":{
                    "$t":"http://www.google.com/m8/feeds/contacts/anthonyclever%40gmail.com/base/61b3ab1c0a42cf0f"
                },
                "updated":{
                    "$t":"2011-09-01T21:12:15.785Z"
                },
                "app$edited":{
                    "xmlns$app":"http://www.w3.org/2007/app",
                    "$t":"2011-09-01T21:12:15.785Z"
                },
                "category":[
                    {
                        "scheme":"http://schemas.google.com/g/2005#kind",
                        "term":"http://schemas.google.com/contact/2008#contact"
                    }
                ],
                "title":{
                    "$t":""
                },
                "link":[
                    {
                        "rel":"http://schemas.google.com/contacts/2008/rel#photo",
                        "type":"image/*",
                        "href":"https://www.google.com/m8/feeds/photos/media/anthonyclever%40gmail.com/61b3ab1c0a42cf0f"
                    },
                    {
                        "rel":"self",
                        "type":"application/atom+xml",
                        "href":"https://www.google.com/m8/feeds/contacts/anthonyclever%40gmail.com/full/61b3ab1c0a42cf0f"
                    },
                    {
                        "rel":"edit",
                        "type":"application/atom+xml",
                        "href":"https://www.google.com/m8/feeds/contacts/anthonyclever%40gmail.com/full/61b3ab1c0a42cf0f"
                    }
                ],
                "gd$email":[
                    {
                        "rel":"http://schemas.google.com/g/2005#other",
                        "address":"sbarrier@superiorbungee.com",
                        "primary":"true"
                    }
                ]
            },
            {
                "gd$etag":"\"Rn89eTZXLSt7I2A9WhNaF0UMTwU.\"",
                "id":{
                    "$t":"http://www.google.com/m8/feeds/contacts/anthonyclever%40gmail.com/base/6d842d410d0b029e"
                },
                "updated":{
                    "$t":"2013-02-02T06:33:37.161Z"
                },
                "app$edited":{
                    "xmlns$app":"http://www.w3.org/2007/app",
                    "$t":"2013-02-02T06:33:37.161Z"
                },
                "category":[
                    {
                        "scheme":"http://schemas.google.com/g/2005#kind",
                        "term":"http://schemas.google.com/contact/2008#contact"
                    }
                ],
                "title":{
                    "$t":"Carrie Clever"
                },
                "content":{
                    "$t":""
                },
                "link":[
                    {
                        "rel":"http://schemas.google.com/contacts/2008/rel#photo",
                        "type":"image/*",
                        "href":"https://www.google.com/m8/feeds/photos/media/anthonyclever%40gmail.com/6d842d410d0b029e",
                        "gd$etag":"\"bxVdYlFEWit7I2BcPR8WWBx7Q3Y_BEkfaSU.\""
                    },
                    {
                        "rel":"self",
                        "type":"application/atom+xml",
                        "href":"https://www.google.com/m8/feeds/contacts/anthonyclever%40gmail.com/full/6d842d410d0b029e"
                    },
                    {
                        "rel":"edit",
                        "type":"application/atom+xml",
                        "href":"https://www.google.com/m8/feeds/contacts/anthonyclever%40gmail.com/full/6d842d410d0b029e"
                    }
                ],
                "gd$name":{
                    "gd$fullName":{
                        "$t":"Carrie Clever"
                    },
                    "gd$givenName":{
                        "$t":"Carrie"
                    },
                    "gd$familyName":{
                        "$t":"Clever"
                    }
                },
                "gd$organization":[
                    {
                        "rel":"http://schemas.google.com/g/2005#other",
                        "gd$orgName":{
                            "$t":"Superior Bungee Corporation"
                        }
                    }
                ],
                "gd$email":[
                    {
                        "rel":"http://schemas.google.com/g/2005#other",
                        "address":"chardonnay15@charter.net",
                        "primary":"true"
                    }
                ],
                "gd$phoneNumber":[
                    {
                        "rel":"http://schemas.google.com/g/2005#mobile",
                        "$t":"12562444255"
                    }
                ],
                "gd$structuredPostalAddress":[
                    {
                        "rel":"http://schemas.google.com/g/2005#home",
                        "gd$formattedAddress":{
                            "$t":"85 Dale Dr.\nScottsboro, Al 35769"
                        },
                        "gd$street":{
                            "$t":"85 Dale Dr."
                        },
                        "gd$postcode":{
                            "$t":"35769"
                        },
                        "gd$city":{
                            "$t":"Scottsboro"
                        },
                        "gd$region":{
                            "$t":"Al"
                        }
                    }
                ],
                "gContact$groupMembershipInfo":[
                    {
                        "deleted":"false",
                        "href":"http://www.google.com/m8/feeds/groups/anthonyclever%40gmail.com/base/6"
                    },
                    {
                        "deleted":"false",
                        "href":"http://www.google.com/m8/feeds/groups/anthonyclever%40gmail.com/base/20dd23b50bdaba24"
                    }
                ]
            },
            {
                "gd$etag":"\"RXo4cTVSLit7I2A9WhJXEkQORQE.\"",
                "id":{
                    "$t":"http://www.google.com/m8/feeds/contacts/anthonyclever%40gmail.com/base/7181e36b8e93d23b"
                },
                "updated":{
                    "$t":"2012-08-06T23:04:14.439Z"
                },
                "app$edited":{
                    "xmlns$app":"http://www.w3.org/2007/app",
                    "$t":"2012-08-06T23:04:14.439Z"
                },
                "category":[
                    {
                        "scheme":"http://schemas.google.com/g/2005#kind",
                        "term":"http://schemas.google.com/contact/2008#contact"
                    }
                ],
                "title":{
                    "$t":"James Cook"
                },
                "link":[
                    {
                        "rel":"http://schemas.google.com/contacts/2008/rel#photo",
                        "type":"image/*",
                        "href":"https://www.google.com/m8/feeds/photos/media/anthonyclever%40gmail.com/7181e36b8e93d23b",
                        "gd$etag":"\"KjB2LgFHSit7I2BbUU0wcw9rO2saKXsMYA0.\""
                    },
                    {
                        "rel":"self",
                        "type":"application/atom+xml",
                        "href":"https://www.google.com/m8/feeds/contacts/anthonyclever%40gmail.com/full/7181e36b8e93d23b"
                    },
                    {
                        "rel":"edit",
                        "type":"application/atom+xml",
                        "href":"https://www.google.com/m8/feeds/contacts/anthonyclever%40gmail.com/full/7181e36b8e93d23b"
                    }
                ],
                "gd$name":{
                    "gd$fullName":{
                        "$t":"James Cook"
                    },
                    "gd$givenName":{
                        "$t":"James"
                    },
                    "gd$familyName":{
                        "$t":"Cook"
                    }
                },
                "gd$email":[
                    {
                        "rel":"http://schemas.google.com/g/2005#other",
                        "address":"jcook@pykl.com",
                        "primary":"true"
                    }
                ],
                "gContact$groupMembershipInfo":[
                    {
                        "deleted":"false",
                        "href":"http://www.google.com/m8/feeds/groups/anthonyclever%40gmail.com/base/6"
                    }
                ]
            }
        ]
    }
}